### ISSUE TITLE
Basic timeseries plots of data

### ISSUE THREAD

**Issue by hetland** [adv-py-geos/Easterwood_rain#3]
Create plots of the data as timeseries.

**Comment by dylanschlichting** [comment]
Make basic plots of data. Most of my work with sar data is making pretty plots - so I can continue that here. 

Specifics TBD

**Comment by askia97** [comment]
On to you

**Comment by dylanschlichting** [comment]
Added time series plots of data with sns. Please reopen this issue if you want modifications
