### ISSUE TITLE
Basic statistical analysis of data

### ISSUE THREAD

**Issue by hetland** [adv-py-geos/Easterwood_rain#4]
Means and standard deviations of all columns of data

**Comment by a-vanderheiden** [comment]
Don't forget the histograms!

**Comment by askia97** [comment]
Do you want a histogram of all column of data?

**Comment by a-vanderheiden** [comment]
Yeah, I think we should have a separate histogram for each variable we're dealing with

**Comment by dylanschlichting** [comment]
Plots are done - ready for stats.
